[package]
name = "homebox-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"
log4rs = { version = "1.0", features = ["json_encoder"] }
structopt = "0.3"
actix-web = "3"
actix-session = "0.4"
async-graphql-actix-web = "2.10"
async-graphql = { version = "2.10.2", features = [ "log", "chrono", "uuid" ] }
uuid = { version = "0.8", features = [ "v4" ] }
chrono = { version = "0.4", features = [ "serde" ] }
serde = { version = "1.0", features = [ "serde_derive" ] }
serde_yaml = "0.8"
bson = "2.0"
rocksdb = "0.17"
