logging:
  appenders:
    stdout:
      kind: console
  root:
    level: debug
    appenders:
      - stdout

server:
  address: 127.0.0.1:3000

database:
  file: homebox-files.db
  metadata: sqlite:homebox.db

auth:
  password: 123abc
