logging:
  appenders:
    stdout:
      kind: console
  root:
    level: debug
    appenders:
      - stdout

server:
  address: 0.0.0.0:3000

database:
  file: homebox-files.db
  metadata: sqlite:homebox.db

auth:
  password: 123abc
